version: '3.5'

services:
  mordor-caldera:
    image: cyb3rward0g/mordor-caldera:0.0.1
    container_name: mordor-caldera
    volumes:
      - ./config/a93f6915-a9b8-4a6b-ad46-c072963b32c1.yml:/opt/Caldera/plugins/evals_caldera/data/facts/a93f6915-a9b8-4a6b-ad46-c072963b32c1.yml
      - ./config/local.yml:/opt/Caldera/conf/local.yml
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    networks:
      caldera:

networks:
  caldera:
    driver: bridge
